### ISSUE TITLE
Switching HDMI Audio out between multiple monitors

### ISSUE THREAD

**Issue by sambul13** [xenolightning/AudioSwitcher_v1#1848]
Pls add switching HDMI Audio out between multiple monitors with integrated speakers. The monitors are connected to HDMI ports of the same or different video cards. Currently HDMI audio out can only be switched by selecting another monitor as Main in Windows 10 Display Panel, and then rebooting the PC.

**Comment by xenolightning** [comment]
That sounds like a nightmare.

Because it has to with display/display drivers, and doesn't use any of the standard windows audio libraries I'm going to out-of-scope this.

Audio Switcher won't ever include display manipulation as part of it's core functionality, it could come as part of a third party plugin at a later date.

Try https://sourceforge.net/projects/monitorswitcher/, I don't know if it will help, but it might make things a little easier.

**Comment by sambul13** [comment]
May be switching the Main monitor in Windows and restarting HDMI Audio  
driver will do the trick? Or, activating Stereo Mix device in Recording  
Devices, and assigning it to listen to HDMI Device Output? You just need  
to be a little creative. Multi-monitor programs won't help, they avoid  
Audio Controls.

**Comment by xenolightning** [comment]
Who knows if it's even possible. It sounds like a stab in the dark.

Someone would need to confirm a way to change the hdmi output without using any display features for it to be of any use.

I don't have multiple HDMI sound devices, so unless someone wants to donate to fund the investigation of this request, then I won't be doing it.
