### ISSUE TITLE
Virus Alert when updating

### ISSUE THREAD

**Issue by ppzz123** [xenolightning/AudioSwitcher_v1#2175]
Windows 10 home, Avast Free Antivirus

Hi,

I just tried to update AudioSwitcher from within the program itself. First I saw a command prompt that said something like "Closing/Ending audioswitcher" (can't really remember the exact phrase) and +- 10 seconds later Avast informed me that AudioSwitcher.exe has been blocked because it's infected with IDP.ALEXA.51.
Should I be worried?

**Comment by jerrac** [comment]
Norton's did the same thing for me. In my case, not necessarily yours, it was because so few people have used the file. Norton's thinks it's better safe than sorry. Fairly annoying. But I was able to override it and get the file accepted. 

I have no idea if there's a way to get antivirus's to stop this kind of thing...

**Comment by xenolightning** [comment]
Not easily, they are false positives caused by "not many users seeing this file".

It only affects new updates, and there's not a huge amount I can do to prevent it. Will look at releasing a virus scan summary along with each release.
