### ISSUE TITLE
Where can I find log files?

### ISSUE THREAD

**Issue by laithalissa** [xenolightning/AudioSwitcher_v1#2205]
Hi,

I'm experiencing the audioswitcher hanging for a few minutes when I launch it (unresponsive right click menu with no devices listed), it clears up by itself after 3+ minutes:

[
![example](https://user-images.githubusercontent.com/887720/80402692-2e463580-88b6-11ea-8a36-54a9f53354db.png)
](url)

Hovering over this menu gives me the spinning doughnut of eternal waiting.

I strongly suspect this is not an issue with the application itself, but something funny in my setup. Could you please direct me to where I might be able to inspect the logs and figure out what the problem is?

Window version: 1903
Audioswitcher v: 1.8.0.142

Cheers,
Laith

**Comment by xenolightning** [comment]
Hi,

The application doesn't have any log output in the portable form - so there won't be anything to find there.

Usually the hang is caused by many sound devices on the same system, on startup it attempts to get the status of each device in the system to cache the results - but having many disconnected/disabled devices can make this take a long time.

**Comment by laithalissa** [comment]
Hi,

I had guessed that was the case because the problem got worse as I added more HDMI devices and headsets. I went ahead and disabled as many as I could but it's still quite sluggish. Honestly the reason I came here is because this is the most sophisticated sound software that I can rely on- the windows sound settings are a train wreck.

Thanks for your reply. Please do comment If you happen to think of something that might help me out.

Thanks for making this application awesome and keeping it free. Much love.
